services:
  jupyter:
    build: .
    ports:
      - "8888:8888"  # Expose Jupyter Notebook
    depends_on:
      - mariadb
    environment: 
      - JUPYTER_ENABLE_LAB=yes
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./notebooks:/app

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"  # Expose MariaDB
    volumes:
      - mariadb_data:/var/lib/mysql  # Persist MariaDB data
      #- ./db_init:/docker-entrypoint-initdb.d # if you want to init a db before the first start

volumes:
  mariadb_data: